// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBegpaGJDgCsycJQrEOr_6tVgqjET5csFk',
    appId: '1:1085015456593:web:ef2c0067a660460c22b170',
    messagingSenderId: '1085015456593',
    projectId: 'todo-app-study',
    authDomain: 'todo-app-study.firebaseapp.com',
    storageBucket: 'todo-app-study.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZxTXMrO164z_-such0nKu9g4TLIrkENI',
    appId: '1:1085015456593:android:905b8b4ad263e3bf22b170',
    messagingSenderId: '1085015456593',
    projectId: 'todo-app-study',
    storageBucket: 'todo-app-study.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0ER_5KY7cRfkyVwBmLU041E-XKmFKXCY',
    appId: '1:1085015456593:ios:f54ce551a8ddbc0622b170',
    messagingSenderId: '1085015456593',
    projectId: 'todo-app-study',
    storageBucket: 'todo-app-study.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );
}
